
service:
  code: 01
  version: @project.version@
server:
  port: 80
datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  username: root
  password: 123456
druid:
  pool:
    size:
      max: 100
      min: 5
      init: 5